### ISSUE TITLE
Please provide a detailed usage description

### ISSUE THREAD

**Issue by Adrian-Samoticha** [dhl123/ELISE-2021#1]
I am trying to get ELISE running on my machine (2020 M1 MacBook Air). I have cloned the repository, `cd`'d into `audit` and ran `python3 extract_audit.py -input audit_log_1`, as instructed in the README.

However, the file `audit_log_1` does not exist in the repo. I have, therefore, created it myself, however I am unsure as to how its contents should look like.

Line 16 in file `extract_audit.py` reads
````py
data_=data.split("}{")[:-1]
````
which means that the input file should contain (multiple?) occurrences of `}{`?

I have read the paper _“ELISE: A Storage Efficient Logging System Powered by Redundancy Reduction and Representation Learning”_, and could not find an example file that satisfies that requirement.

Would you mind helping me out?

**Comment by dhl123** [comment]
Hi,

Thanks for the question. Please run darpa example or see [onedrive](https://rutgersconnect-my.sharepoint.com/:f:/g/personal/hd294_cs_rutgers_edu/ElIxE7bqVpZBuiB7gnVTQkoBTdKrAkL0IVuRkUEEeBYSqQ?e=kpceGz) for a sample audit log file. If you still have questions, please let me know.
